import { ManageConferenceParticipantRequest } from '../../manage-conference-participant-request';

export interface GetConferenceInfoRequestData {
  /** The unique identifier of the conference. The user sets this value. */
  'conferenceId': string;
}
export interface KickAllRequestData {
  /** The unique identifier of the conference. The user sets this value. */
  'conferenceId': string;
}
export interface KickParticipantRequestData {
  /** The unique identifier of the call. This value is generated by the system. */
  'callId': string;
  /** The unique identifier of the conference. The user sets this value. */
  'conferenceId': string;
}
export interface ManageParticipantRequestData {
  /** The unique identifier of the call. This value is generated by the system. */
  'callId': string;
  /** The unique identifier of the conference. The user sets this value. */
  'conferenceId': string;
  /**  */
  'manageParticipantRequestBody'?: ManageConferenceParticipantRequest;
}
