import { SVAMLRequestBody } from '../../svaml-request-body';

export interface GetCallResultRequestData {
  /** The unique identifier of the call. This value is generated by the system. */
  'callId': string;
}
export interface ManageWithCallLegRequestData {
  /** The unique identifier of the call. This value is generated by the system. */
  'callId': string;
  /** Specifies which part of the call will be managed. This option is used only by the `PlayFiles` and `Say` instructions to indicate which channel the sound will be played on. Valid options are `caller`, `callee` or `both`. If not specified, the default value is `caller`.</br><Warning>The `callLeg` identifier is ignored for calls that are part of a conference and calls initiated using the Callout API.</Warning> */
  'callLeg': 'caller' | 'callee' | 'both';
  /**  */
  'manageWithCallLegRequestBody'?: SVAMLRequestBody;
}
export interface UpdateCallRequestData {
  /** The unique identifier of the call. This value is generated by the system. */
  'callId': string;
  /**  */
  'updateCallRequestBody'?: SVAMLRequestBody;
}
