export type {
  SmartConversationsEvent,
  SmartConversationNotification,
  AnalysisResult,
  MachineLearningSentimentResult,
  SentimentResult,
  MachineLearningNLUResult,
  IntentResult,
  MachineLearningImageRecognitionResult,
  DocumentImageClassification,
  OpticalCharacterRecognition,
  OpticalCharacterRecognitionData,
  DocumentFieldClassification,
  DocumentFieldClassificationData,
  MachineLearningPIIResult,
  OffensiveAnalysis,
} from './smart-conversations-event';
