import { Mailgun } from '../../../../../src';

export const sendEmailRequestWithHtml: Mailgun.SendEmailRequest = {
  from: 'from value',
  to: 'to value',
  cc: 'cc value',
  bcc: 'bcc value',
  subject: 'subject value',
  text: 'text value',
  html: 'html value',
  ampHtml: 'amp_html value',
  attachment: 'attachment value',
  inline: 'inline value',
  overrideProperties: {
    tag: 'tag value',
    sendingIp: 'sendingIp value',
    sendingIpPool: 'sendingIpPool value',
    deliveryTime: 'deliveryTime value',
    deliveryTimeOptimizePeriod: 24,
    enableDkimSignature: 'yes',
    secondaryDkim: 'secondaryDkim value',
    secondaryDkimPublic: 'secondaryDkimPublic value',
    requireTls: false,
    skipVerification: true,
    timeZoneLocalize: '02:00PM',
    tracking: 'htmlonly',
    trackingClicks: 'htmlonly',
    trackingOpens: 'yes',
    trackingPixelLocationTop: 'no',
    isTestMode: false,
  },
  'h:X-Mailgun-Sending-Ip-Pool': 'xx.xx.xxx.x',
  'v:first_name': 'John',
  'v:last_name': 'Smith',
  'v:my_message_id': 123,
};

export const sendEmailRequestWithTemplate: Mailgun.SendEmailRequest = {
  from: 'from value',
  to: 'to value',
  cc: 'cc value',
  bcc: 'bcc value',
  subject: 'subject value',
  text: 'text value',
  template: 'template value',
  ampHtml: 'amp_html value',
  attachment: 'attachment value',
  inline: 'inline value',
  templateProperties: {
    version: 'version value',
    text: 'yes',
    variables: 'variables value',
  },
  overrideProperties: {
    tag: 'tag value',
    sendingIp: 'sendingIp value',
    sendingIpPool: 'sendingIpPool value',
    deliveryTime: 'deliveryTime value',
    deliveryTimeOptimizePeriod: 36,
    enableDkimSignature: true,
    secondaryDkim: 'secondaryDkim value',
    secondaryDkimPublic: 'secondaryDkimPublic value',
    requireTls: 'yes',
    skipVerification: 'no',
    timeZoneLocalize: '04:15AM',
    tracking: 'yes',
    trackingClicks: 'no',
    trackingOpens: true,
    trackingPixelLocationTop: false,
    isTestMode: false,
  },
  'h:X-Mailgun-Sending-Ip-Pool': 'xx.xx.xxx.x',
  'v:first_name': 'John',
  'v:last_name': 'Smith',
  'v:my_message_id': 123,
};
