import { Mailgun } from '../../../../../src';

export const sendEmailRequestWithHtml: Mailgun.SendEmailRequest = {
  from: 'from value',
  to: 'to value',
  cc: 'cc value',
  bcc: 'bcc value',
  subject: 'subject value',
  text: 'text value',
  html: 'html value',
  ampHtml: 'amp_html value',
  attachment: 'attachment value',
  inline: 'inline value',
  overrideProperties: {
    tag: 'tag value',
    sendingIp: 'sendingIp value',
    sendingIpPool: 'sendingIpPool value',
    deliveryTime: new Date('2024-06-06T13:42:42Z'),
    deliveryTimeOptimizePeriod: 24,
    enableDkimSignature: true,
    secondaryDkim: 'secondaryDkim value',
    secondaryDkimPublic: 'secondaryDkimPublic value',
    requireTls: false,
    skipVerification: true,
    timeZoneLocalize: '02:00PM',
    tracking: 'htmlonly',
    trackingClicks: 'htmlonly',
    trackingOpens: 'yes',
    trackingPixelLocationTop: 'no',
    isTestMode: false,
  },
  customHeaders: {
    'X-Mailgun-Sending-Ip-Pool': 'xx.xx.xxx.x',
  },
  customVariables: {
    'first_name': 'John',
    'last_name': 'Smith',
    'my_message_id': 123,
  },
};

export const sendEmailRequestWithTemplate: Mailgun.SendEmailRequest = {
  from: 'from value',
  to: 'to value',
  cc: 'cc value',
  bcc: 'bcc value',
  subject: 'subject value',
  text: 'text value',
  template: 'template value',
  ampHtml: 'amp_html value',
  attachment: 'attachment value',
  inline: 'inline value',
  templateProperties: {
    version: 'version value',
    text: true,
    variables: {
      orders: [
        {
          id: 123,
          name: 'Dark Chocolate Box',
        },
        {
          id: 456,
          name: 'Calissons x12',
        },
      ],
    },
  },
  overrideProperties: {
    tag: 'tag value',
    sendingIp: 'sendingIp value',
    sendingIpPool: 'sendingIpPool value',
    deliveryTime: new Date('2024-06-06T13:42:42Z'),
    deliveryTimeOptimizePeriod: 36,
    enableDkimSignature: true,
    secondaryDkim: 'secondaryDkim value',
    secondaryDkimPublic: 'secondaryDkimPublic value',
    requireTls: true,
    skipVerification: false,
    timeZoneLocalize: '04:15AM',
    tracking: 'yes',
    trackingClicks: 'no',
    trackingOpens: true,
    trackingPixelLocationTop: false,
    isTestMode: false,
  },
  customHeaders: {
    'X-Mailgun-Sending-Ip-Pool': 'xx.xx.xxx.x',
  },
  customVariables: {
    'first_name': 'John',
    'last_name': 'Smith',
    'my_message_id': 123,
  },
};
